name: CI

on:
  release:
    types:
      - created
      - unpublished

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js Modules
        run: npm i

      - name: Build and deploy
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Zip (Win32)
        if: runner.os == 'windows'
        run: tar.exe -a -c -f out/build.zip out/*
      - name: Upload Release Asset (Win32)
        if: runner.os == 'windows'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/build.zip
          asset_name: xstore-desktop-${{ runner.os }}.zip
          asset_content_type: application/zip

      - name: Zip (*nix)
        if: runner.os == 'linux' || runner.os == 'macos'
        run: tar -zcvf ./out/build.tar.gz out/*
      - name: Upload Release Asset (*nix)
        if: runner.os == 'linux' || runner.os == 'macos'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./out/build.tar.gz
          asset_name: xstore-desktop-${{ runner.os }}.tar.gz
          asset_content_type: application/gzip