name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js Modules
        run: npm i

      - name: Build and deploy
        run: npm run webpack:bundle