name: CI

on:
  push:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest , macos-latest]
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js Modules
        run: npm i

      - name: Build and deploy
        run: npm run package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}